In [1]:
import numpy as np
import random

In [2]:
#az első kódblokk, amely két listát definiál
elso_lista=[10,20,30,40]
masodik_lista=[1,2,3,4,5]

for tizes in elso_lista:
    #a második kódblokk (végigmegy az elso_lista elemein)
    print('Belépés a második kódblokkba') 
    for egyes in masodik_lista:
        #minden tizes esetében végigmegy a masodik_lista elemein)
        uj_szam=tizes+egyes
        print('A harmadik kódblokk eredménye; Az új szám:', uj_szam)


Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 11
A harmadik kódblokk eredménye; Az új szám: 12
A harmadik kódblokk eredménye; Az új szám: 13
A harmadik kódblokk eredménye; Az új szám: 14
A harmadik kódblokk eredménye; Az új szám: 15
Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 21
A harmadik kódblokk eredménye; Az új szám: 22
A harmadik kódblokk eredménye; Az új szám: 23
A harmadik kódblokk eredménye; Az új szám: 24
A harmadik kódblokk eredménye; Az új szám: 25
Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 31
A harmadik kódblokk eredménye; Az új szám: 32
A harmadik kódblokk eredménye; Az új szám: 33
A harmadik kódblokk eredménye; Az új szám: 34
A harmadik kódblokk eredménye; Az új szám: 35
Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 41
A harmadik kódblokk eredménye; Az új szám: 42
A harmadik kódblokk eredménye; Az új szám: 43
A harmadik kódblokk eredménye; Az új szám: 44
A harmadik

In [3]:
# Példák a print függvény kimenetének többféle formázására
print('{} {}'.format('egy', 'kettő'))
print('{} {}'.format(1,2))
print('Pi= {}'.format(3.14159))
print('Pi= {0:8.2f}'.format(3.14159))

egy kettő
1 2
Pi= 3.14159
Pi=     3.14


In [4]:
# egész érték változóhoz rendelése:
myint = 9
print('example integer is ', myint)

# lebegőpontos érték hozzárendelése:
myfloat1=9.3
myfloat2=float(9)
print('example integer is ', myfloat1)
print('casting an integer as a float results in', myfloat2)

# Logikai változók deklarálása:
mybool1 = True
mybool2 = False
print('example booleans are ', mybool1, ' and ', mybool2)

# A szövegek egyszeres vagy dupla idézőjellel definiálhatók: 
string1="hello world"
string2='hello world'
print (string1)
print(string2)
print('testing if string1 and string2 are equal:', string1==string2)

# Példák a szövegeken alkalmazható függvényekre:
s = "hello"
# A string első karakterét nagybetűssé alakítja, a többit kicsivé.
print(s.capitalize())  
# A teljes stringet nagybetűssé alakítja.
print(s.upper())    
# A szöveget jobbra igazítja, és 7 karakter hosszúságúra bővíti úgy, hogy a bal oldalon szóközöket ad hozzá.   
print(s.rjust(7))  
# A szöveget középre igazítja, és 7 karakter hosszúságúra bővíti úgy, hogy szóközöket ad hozzá mindkét oldalán.   
print(s.center(7))     
 # Minden 'l' karaktert '(ell)'-re cserél.
print(s.replace('l', '(ell)')) 
# Eltávolítja a vezető és záró szóközöket a stringből.
print('  world '.strip())


example integer is  9
example integer is  9.3
casting an integer as a float results in 9.0
example booleans are  True  and  False
hello world
hello world
testing if string1 and string2 are equal: True
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [ ]:
# Egyszerű matematikai műveletek példái:
print('összeadás:', 2+3)
print('kivonás:', 2-3)
print('szorzás:', 2*3)
print('osztás:', 2/3)
# A maradék operátor ('%') az osztás utáni egész szám maradékát adja vissza::
a=9
b=5
print('the remainder following division of {} by {} is {}'.format(a, b, a%b))
# A '*' kétszeri használata ('**') hatványozást eredményez
a=2
b=4
print('{} to the power {} is {}'.format(a, b, a**b))

In [5]:
a=10
print(a==10)
print(a<12)
print(a>20)

# Két feltételes kifejezés egyidejű értékelése 'and', 'or' és 'is' operátorokkal
a=10
b=12
print(a is b)
print(a< 15 and b > 10)
print (a < 15 or b < 10)

# A "not" operátor a logikai kifejezés negálására szolgál:
print(not a is b)

True
True
False
False
True
True
True


In [6]:
# Megoldások

# Q1. Definiáljunk változókat és írjuk ki őket
a=8 
b=7
teststr='Hello World'
print(teststr)
print("a={} and b={}" .format(a, b))


# Q2. Gyakoroljuk a print utasításokat pl. print('hello world')
print('hello world')

# Q3. Próbáljuk ki a teststr változó kiíratását (mi történik, ha dupla idézőjeleket használunk?)
teststr="Hello World"
print(teststr)

# Q4. Próbáljuk meg hozzáadni az 'a' változót a 'teststr' változóhoz egy print utasításban
print('{} {}'.format(teststr,a))
print(teststr +' '+ str(a))
print(f"{teststr} {a}")

Hello World
a=8 and b=7
hello world
Hello World
Hello World 8
Hello World 8
Hello World 8


In [7]:
# Gyakorlat 2 megoldások

# Q1. Próbáljunk ki egyszerű matematikai műveleteket, írjuk ki az eredményt:
a=8 
b=7

print(' a+b = {}'.format(a+b))
print(' a-b = {}'.format(a-b))
print(' a*b = {}'.format(a*b))
print(' a/b = {:.2f}'.format(a/b))

# Q2. Matematikai operátorok kombinációja, próbáljuk kombinálni a matematikai operátorokat pl. a*a+b - a/b 
print(' a*a+b - a/b = {:.2f}' . format(a*a+b-a/b))

# Q3 Mi történik a zárójelek hozzáadásával pl. a*(a+b - a/b) vagy (a*a+b - a)/b
print(' a*(a+b - a/b) =  {:.2f}' . format(a*(a+b - a/b)))
print(' (a*a+b - a)/b =  {:.2f}' .format((a*a+b -a)/b))

 a+b = 15
 a-b = 1
 a*b = 56
 a/b = 1.14
 a*a+b - a/b = 69.86
 a*(a+b - a/b) =  110.86
 (a*a+b - a)/b =  9.00


In [8]:
# Gyakorlat 3 megoldások

# Q1. Változók definiálása 

a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 Értékeljük az alábbi feltételes állításokat
print('a==b',a==b)
print('2*a==b',2*a==b)
print('a>b',a>b)
print('a<b',a<b)
print('a is b',a is b)
print('2*a is b',2*a is b)

# Q3. Kombináljuk a feltételeket and/or operátorokkal és írjuk ki az eredményt. Például: 'a == b or b> a' 
print(a==b or b>a)

# Q4. Próbáljuk meg az állítások inverzét a not operátorral
print(not(a==b or b>a))

a==b
2*a==b
a>b
a<b
a is b
2*a is b


In [9]:
emptylist=[] # Üres lista
integerlist=[1,2,3,4,5,6] #Egész számokat tartalmazó lista
stringlist=['string1', 'string2', 'string3'] #Szövegeket tartalmazó lista
mixedlist=[10, "some string", 4.2, 2, 'some other string'] #Vegyes típusú adatokat tartalmazó lista
# beágyazott lista
nestedlist=[['dog','cat','pig'], [1,2,3 ,4], [10, "some string", 4.2, 2, 'some other string'] ]

In [10]:
teststr = 'Hello World'
print('a harmadik elem az egész számok listájában', integerlist[2])
print('a negyedik elem a vegyes lista elemei között', mixedlist[3])
print('a hetedik elem a szövegben', teststr[6])

# figyeljük meg, hogy a szeletelés az összes elemet tartalmazza a megadott indexig, de a záró indexet nem
print('a középső két elem az egész számok listájában', integerlist[2:4])
# szeletelés a kezdetektől az 5. elemig
print('a kezdetektől a 4. elemig', integerlist[:4])
# szeletelés a 4. elemtől a végéig
print('a 4. elemtől a végéig', integerlist[3:])
# szeletelés a 4. elemtől egy elemmel a vég előtt
print('a 4. elemtől egy elemmel a vég előtt', integerlist[3:-1])
# Az indexálás fordítva is elvégezhető:
print('fordított indexálás', integerlist[::-1])
# vagy nagyobb lépések használatával:
print('minden második elem', integerlist[::2])

a harmadik elem az egész számok listájában 3
a negyedik elem a vegyes lista elemei között 2
a hetedik elem a szövegben W
a középső két elem az egész számok listájában [3, 4]
a kezdetektől a 4. elemig [1, 2, 3, 4]
a 4. elemtől a végéig [4, 5, 6]
a 4. elemtől egy elemmel a vég előtt [4, 5]
fordított indexálás [6, 5, 4, 3, 2, 1]
minden második elem [1, 3, 5]


In [11]:
integerlist.append(7)
print('az új egész számok listája', integerlist)
print('az új egész számok lista hossza', len(integerlist))
print('a teststr hosszúsága', len(teststr))
print(integerlist+stringlist)
integerlist[3] = 'kicserélt elem'
print(integerlist)

az új egész számok listája [1, 2, 3, 4, 5, 6, 7]


In [12]:
# Gyakorlat 1 megoldás.

mylist=[1,2,3,4,5]

# index alapján irassuk ki a mylist elemeit 

print(mylist[0],mylist[1],mylist[3])

# index alapján írjuk ki a lista utolsó elemét

print(mylist[-1])

# index segítségével irassuk ki a lista egy szeletét

print(mylist[1:3])

# adjunk a listához egy új elemet

mylist.append(43110)

1 2 4
5
[2, 3]


In [13]:
# Gyakorlat 2 megoldás

string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Q1 Két sztring és két lista összefűzése

print(string1+string2)
print(list1+list2)

# Q2  10 másolat összefűzése

print(string1*10)

HelloWorld
['Hello', 'World', "I'm", 'ready', 'toPython']
HelloHelloHelloHelloHelloHelloHelloHelloHelloHello


In [15]:
current_thing = "NUMPY"

In [16]:
# Létrehozunk egy 1D tömböt
a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
# Módosítjuk a tömb egy elemét
a[0] = 5                  
print(a)                 
# Hozzunk létre egy 2D tömböt
b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [17]:
# Hozzunk létre egy 2x2-es tömböt, amelynek minden eleme 0
a = np.zeros((2,2))   
print(a)             

# Hozzunk létre egy 1x2-es tömböt, amelynek minden eleme 1
b = np.ones((1,2))    
print(b)              

# Hozzunk létre egy 2x2-es konstans tömböt, ahol minden elem 7
c = np.full((2,2), 7)  
print(c)              

# Hozzunk létre egy 2x2-es egység mátrixot. A 2x2-es egység mátrix egy négyzetes mátrix, amelynek minden átlón kívüli eleme 0, míg az átlójában lévő elemek mind 1-esek.
d = np.eye(2)         
print(d)              

# Hozzunk létre egy 2x2-es tömböt, amelyet véletlenszerű értékek töltenek ki
e = np.random.random((2,2))  
print(e)      

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.22004624 0.50159758]
 [0.35178781 0.32351778]]


In [18]:
# Hozzunk létre egy 2D tömböt (3, 4) alakzattal
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

# Használjunk szeletelést a tömb első 2 sorának és 1-2. oszlopának kiválasztására
b = a[:2, 1:3]
print(b)

# Figyeljük meg, hogy a szeletelés egy módja annak, hogy megtekintsük a tömb adatait,
# és ez azt jelenti, hogy a két objektum adatai megosztottak. Ezért ha módosítjuk a 'b'-t,
# akkor az eredeti tömb is módosulni fog.
print(a[0, 1])   # Eredetileg: 2
b[0, 0] = 77     # Módosítjuk a 'b' első elemét
print(a[0, 1])   # Az eredeti tömb is módosult: 77

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [19]:
# Hozzuk létre a következő, (3, 4) alakú, 2D tömböt
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Ha a második sort szeretnénk kiválasztani, annak két módja van.
# Ha egy sorhoz/oszlophoz egész számokkal indexelve férünk hozzá (a[1, :] vagy a[:, 1]), 1D tömböt kapunk.
# Ha szeleteléssel (a[1:2, :] vagy a[:, 1:2]), 2D tömböt kapunk, amely megőrzi az eredeti dimenziókat.
row_r1 = a[1, :]    # Az 'a' második sorának 1D nézete
row_r2 = a[1:2, :]  # Az 'a' második sorának 2D nézete
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

# Ugyanez vonatkozik a tömb oszlopainak elérésére is:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [20]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Keressük meg azokat az elemeket az 'a' tömbben, amelyek nagyobbak, mint 2.
# Ez egy olyan NumPy tömböt ad vissza, amely Booleán értékeket tartalmaz, és ugyanolyan alakú, mint 'a'.
# A bool_idx jelzi azt, hogy az adott elem nagyobb-e, mint 2.
bool_idx = (a > 2)   

print(bool_idx)     

# Boolean tömb indexelést használunk egy 1D tömb létrehozásához,
# amely csak azokat az elemeket tartalmazza, ahol a bool_idx értéke True.
print(a[bool_idx])  

# A fenti műveletet egyetlen rövid utasítással is végrehajtható:
print(a[a > 2]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [21]:
# Gyakorlat 1 megoldás
l = [12.23, 13.32, 100, 36.32]
print("Eredeti lista:",l)
a = np.array(l)
print("Egydimenziós NumPy tömb: ",a)

Eredeti lista: [12.23, 13.32, 100, 36.32]
Egydimenziós NumPy tömb:  [ 12.23  13.32 100.    36.32]


In [22]:
# Gyakorlat 2 megoldás
x = np.zeros(10)
print(x)
print("A hetedik elem értékének frissítése 11-re")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
A hetedik elem értékének frissítése 11-re
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [23]:
# Gyakorlat 3 megoldás
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [24]:
# Gyakorlat 4 megoldás
x = np.ones((3,3))
print("Sakktábla mintázat:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Sakktábla mintázat:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
# Gyakorlat 5 megoldás
x = [10, 20, 30]
print("Eredeti tömb:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("A további értékek hozzáadását követően:")
print(x)

Eredeti tömb:
[10, 20, 30]
A további értékek hozzáadását követően:
[10 20 30 40 50 60 70 80 90]


In [26]:
# Gyakorlat 6 megoldás
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("A két tömb közös értékei:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
A két tömb közös értékei:
[10 40]


In [27]:

LVEF = int(input('Adja meg az LVEF (left ventricular ejection fraction)  értéket: '))

if LVEF > 50:
    print('HFpEF (heart failure with preserved ejection fraction)')
else:
    if LVEF < 40:
        print('HFrEF (heart failure with reduced ejection fraction)')
    else:
        print('HFmEF (heart failure with mildly reduced ejection fraction)')

Adja meg az LVEF (left ventricular ejection fraction)  értéket:  10


HFrEF (heart failure with reduced ejection fraction)


In [28]:
name = "John"
if name in ["John", "Dave"]:
    print("A személy neve vagy John vagy Dave.")

A személy neve vagy John vagy Dave.


In [29]:
BMI=20

if BMI <= 18.5: 
    print('A személy alultáplált.')
elif BMI > 18.5 and BMI <=25.0:
    print('A személy normál súlyú.')
elif BMI > 25.0 and BMI <=30.0 :
    print('A személy túlsúlyos.')
else:
    print('A személy elhízott.')

A személy normál súlyú.


In [30]:
#Életfunkciót értékelő pontszám bekérése
ViEWS = int(input('Please introduce value for ViEWS: '))
#A betegnél előfordult szívritmuszavar (1: igen, 0: nem) bekérése:
arrhythmia = int(input('Please introduce fatal arrhythmia status (yes = 1, no = 0):'))
#Diabétesz előfordulása (1: igen, 0: nem):
diabetes = int(input('Please introduce diabetes status (yes = 1, no = 0):'))
#A szívelégtelenség súlyosságát jelző osztály (1–4, ahol 1 a legenyhébb, 4 a legsúlyosabb):
Killip = int(input('Please introduce Killip class (class І = 1, II = 2, III = 3, IV = 4):'))
#BUN érték:
BUN = int(input('Please introduce value for blood urea nitrogen (BUN):'))
#Szívspecifikus troponin I érték:
cTnI = int(input('Please introduce value for cardiac troponin I (cTnI):'))
#A beteg életkora:
age = int(input('Please introduce value for age:'))

if ViEWS < 5:
    if arrhythmia:
        if Killip > 2:
            if cTnI >= 28:
                print('High (70%‐100%)')
            else:
                if BUN < 7.9:
                    print('Moderate (40%‐69%)')
                else:
                    print('Low (<40%)')  
        else:
            print('Low (<40%)')

    else:
        print('Low (<40%)')
else:
    if diabetes:
        print('High (70%‐100%)')
    else:
        if age < 64:
            print('Low (<40%)')
        else:
            print('Moderate (40%‐69%)')

Please introduce value for ViEWS:  10
Please introduce fatal arrhythmia status (yes = 1, no = 0): 10
Please introduce diabetes status (yes = 1, no = 0): 10
Please introduce Killip class (class І = 1, II = 2, III = 3, IV = 4): 10
Please introduce value for blood urea nitrogen (BUN): 10
Please introduce value for cardiac troponin I (cTnI): 10
Please introduce value for age: 100


High (70%‐100%)


In [32]:
mylist=[10,20,30,40,50]

for item in mylist:
    print(item)

10
20
30
40
50
0
2
4
6
8


In [33]:
   
for item in range(0,10,2):
    print(item)

0
2
4
6
8


In [34]:
# Az első kódrészlet
# tizesek
elso_lista = [10, 20, 30, 40]  
# egyesek
masodik_lista = [1, 2, 3, 4, 5]

# Az első for ciklus (az elso_lista elemein iterálunk)
for tizes in elso_lista:
    # A második kódrészlet (egy második for ciklus, ami masodik_lista elemein megy végig)
    for egyes in masodik_lista:
        # A harmadik kódrészlet (második lista elemein iterálunk)
        # Minden egyes 'tizes' értékhez hozzáadjuk az 'egyes' értéket.
        uj_szam = tizes + egyes  
        # A harmadik kódrészlet kimenete: Az uj_szam kiszámítása.
        # Az eredmény kiíratása
        print('A harmadik kódrészlet kimenete; Az új szám ', uj_szam)  

A harmadik kódrészlet kimenete; Az új szám  11
A harmadik kódrészlet kimenete; Az új szám  12
A harmadik kódrészlet kimenete; Az új szám  13
A harmadik kódrészlet kimenete; Az új szám  14
A harmadik kódrészlet kimenete; Az új szám  15
A harmadik kódrészlet kimenete; Az új szám  21
A harmadik kódrészlet kimenete; Az új szám  22
A harmadik kódrészlet kimenete; Az új szám  23
A harmadik kódrészlet kimenete; Az új szám  24
A harmadik kódrészlet kimenete; Az új szám  25
A harmadik kódrészlet kimenete; Az új szám  31
A harmadik kódrészlet kimenete; Az új szám  32
A harmadik kódrészlet kimenete; Az új szám  33
A harmadik kódrészlet kimenete; Az új szám  34
A harmadik kódrészlet kimenete; Az új szám  35
A harmadik kódrészlet kimenete; Az új szám  41
A harmadik kódrészlet kimenete; Az új szám  42
A harmadik kódrészlet kimenete; Az új szám  43
A harmadik kódrészlet kimenete; Az új szám  44
A harmadik kódrészlet kimenete; Az új szám  45


In [35]:
lista=['egy','kettő','három','négy','öt']

for index,item in enumerate(lista):
    print(index,item)

0 egy
1 kettő
2 három
3 négy
4 öt


In [36]:
# függvény definíció
def sum(x, y):
    return x + y  # mivel a függvény egyszerű, egy sorban is visszaadható

# függvény alkalmazása

a = 5
b = 10

print('a {} és b {} összege: {}'.format(a, b, sum(a, b)))

a 5 és b 10 összege: 15


In [37]:
# ez a függvény így 2 vagy 3 argumentum összegét is visszaadhatja
def sum2(x, y, z=0):
    return x + y + z 

# függvény alkalmazása

a = 5
b = 10
c = 20

print('a {} és b {} összege: {}'.format(a, b, sum2(a, b)))
print('a {}, b {} és c {} összege: {}'.format(a, b, c, sum2(a, b, c)))

a 5 és b 10 összege: 15
a 5, b 10 és c 20 összege: 35


In [38]:
def sumsub(x, y, z1=0, z2=0):
    return x - y + z1 - z2

# a függvény alkalmazása

a=5
b=10
c=20
d=30

print(sumsub(12,4))
print(sumsub(42,15,z2=10))
print(sumsub(42,15,z1=20, z2=10))

8
17
37


In [39]:
# Vérnyomás függvény
def blood_pressure(systolic_bp, diastolic_bp):
    if (systolic_bp < 120 and diastolic_bp < 80):
        print('Normal')
    elif (120 < systolic_bp <= 129 and diastolic_bp < 80):
        print('Elevated')
    elif (130 <= systolic_bp <= 139 or 80 <= diastolic_bp < 89):
        print('High blood pressure, hypertension stage 1')
    elif (systolic_bp > 180 or diastolic_bp > 120):
        print('High blood pressure. Consult your doctor immediately.')
    elif (140 <= systolic_bp < 180 or 90 <= diastolic_bp < 120):
        print('High blood pressure, hypertension stage 2')

systolic_bp = int(input('Kérem adja meg a szisztolés vérnyomás értékét: '))
diastolic_bp = int(input('Kérem adja meg a diasztolés vérnyomás értékét: '))
blood_pressure(systolic_bp, diastolic_bp)

Kérem adja meg a szisztolés vérnyomás értékét:  100
Kérem adja meg a diasztolés vérnyomás értékét:  10


Normal


In [40]:
# 10 ismétlés a 10 beteg kiértékeléséhez:
for i in np.arange(10):
    #szisztolés vérnyomás generálása 90 és 200 Hgmm között
    systolic_bp = random.randint(90, 200)
    #diasztolés vérnyomás generálása 60 és 130 Hgmm között
    diastolic_bp = random.randint(60, 130)
    #Kiírjuk az aktuális beteg szisztolés és diasztolés vérnyomását
    print('Subject {} -> Systolic bp = {} and diastolic bp = {}'.format(i, systolic_bp, diastolic_bp))
    #Meghívjuk a blood_pressure függvényt, amely kategorizálja a vérnyomást
    blood_pressure(systolic_bp, diastolic_bp)

Subject 0 -> Systolic bp = 119 and diastolic bp = 86
High blood pressure, hypertension stage 1
Subject 1 -> Systolic bp = 127 and diastolic bp = 129
High blood pressure. Consult your doctor immediately.
Subject 2 -> Systolic bp = 127 and diastolic bp = 114
High blood pressure, hypertension stage 2
Subject 3 -> Systolic bp = 197 and diastolic bp = 84
High blood pressure, hypertension stage 1
Subject 4 -> Systolic bp = 133 and diastolic bp = 91
High blood pressure, hypertension stage 1
Subject 5 -> Systolic bp = 191 and diastolic bp = 119
High blood pressure. Consult your doctor immediately.
Subject 6 -> Systolic bp = 184 and diastolic bp = 82
High blood pressure, hypertension stage 1
Subject 7 -> Systolic bp = 162 and diastolic bp = 78
High blood pressure, hypertension stage 2
Subject 8 -> Systolic bp = 94 and diastolic bp = 115
High blood pressure, hypertension stage 2
Subject 9 -> Systolic bp = 186 and diastolic bp = 125
High blood pressure. Consult your doctor immediately.
