
Bevezető: Python és Jupyter notebook
===

# <span style="color:brown"> **Bevezetés**

A Python programozási nyelvet az 1990-es évek elején fejlesztették ki. Ez egy magas szintű, értelmezett, interaktív és objektumorientált nyelv, amelyet úgy terveztek, hogy könnyen használható legyen. 
Azóta a Python népszerűsége jelentősen megnőtt, olyannyira, hogy ma már az egyik legelterjedtebb programozási nyelv a gépi tanulás és az adatelemzéssel foglalkozók körében. 

A Python **értelmezett** és **interaktív**

-  A kód futásidőben kerül feldolgozásra 
-  A végrehajtás előtt nincs szükség előzetes fordításra
-  Ebből következően a kódunk soronként futtatható

Általábanosságban véve a kód egyszerű szerkezetű. A Python hordozható, az egyik operációs rendszeren írt kód egyszerűen átvihető egy másikra. A Python kompatibilis a Unix, Mac OS, Windows, Android és iOS platformokkal. Nyílt forráskódú, és széles fejlesztői, felhasználói közösség támogatja, amely számos jól dokumentált és fejlett csomagot biztosít numerikus és képelemzéshez.

Példák az adatelemzésben leggyakrabban használt csomagokra:

- **`NumPy`** a Python tudományos számításokhoz használt alapcsomagja, amelyet többdimenziós tömbök kezelésére használnak. A Numpy dokumentáció linkje:: https://numpy.org/doc/stable/
- **`scikit-learn`** gépi tanulási könyvtár, amely támogatja a felügyelt és nem felügyelt tanulási módszereket. Emellett számos eszközt biztosít a modellillesztéshez, adatelőkészítéshez, modellválasztáshoz és értékeléshez. Link a dokumentációhoz: https://scikit-learn.org/stable/user_guide.html![image.png](attachment:image.png)
- **`matplotlib`** statikus, animált és interaktív vizualizációk létrehozásához használható csomag. Link a dokumentációhoz: https://matplotlib.org/users/index.html
- **`pandas`** adatkezelő és elemző eszköz. Dokumentáció: https://pandas.pydata.org/docs/user_guide/index.html

# <span style="color:brown"> **Áttekintés**

Az első gyakorlatban áttekintjük a Python nyelv és objektumok alapjait. Jupyter Notebookot fogunk használni, amely egy könnyen használható oktatási és interaktív eszköz, amely lehetővé teszi az írott magyarázatok és kódrészletek kombinálását.

***

# <span style="color:brown"> 1) A Python alapjai

A Jupyter Notebook két különböző billentyűzetbemeneti módot kínál:

- **Command mode** Ez a billentyűzetet a notebook szintű műveletekhez köti. A szürke cella kerete és a kék bal oldali margó jelzi.
- **Edit mode** amikor egy cellában gépel, azt a zöld cella keret jelzi.

Néhány hasznos **billentyűparancs** a Jupyter Notebook használatához:
- ` Shift + Enter` az aktuális cella futtatása
- ` Ctrl + S ` a notebook mentése
- ` Ctrl + Z ` visszavonás

Command Mode:
- ` A ` cella beszúrása felülre
- ` B ` cella beszúrása alulra
- ` X ` kijelölt cellák kivágása
- ` C ` kijelölt cellák másolása
- ` V ` cellák beillesztése alulra


A notebook első része a Python alapjaira összpontosít, beleértve az egyszerű változókat és tuple-öket, listákat, karakterláncokat és matematikai operátorokat, feltételeket és függvényeket.

## <span style="color:brown"> **Rendszerbeállítások**
 
### <span style="color:red"> Fontos: </span> Első lépésben importálni kell azokat a csomagokat, amelyeket a későbbiekben használni fogunk.

- [numpy](www.numpy.org) a tudományos számításokhoz szükséges csomag.
- [random](https://docs.python.org/3/library/random.html) a random számok kezeléséhez szüksége csomag.

In [6]:
import numpy as np
import random

## <span style="color:brown"> 1.1) A kód struktúrálása

A Python az indentálást (behúzást) használja a programok és szkriptek blokkokba szervezésére a kapcsos zárójelek helyett. Minden kódrészletet egy blokkban vízszintesen kell igazítani, úgy, hogy minden sor ugyanonnan kezdődjön balról.

A kódblokk egy olyan Python program szövegrészlet, amelyet egységként lehet végrehajtani. Egy nagyon gyakori példa a kódbetétre egy for ciklus, amelyet hagyományosan akkor használnak, ha van egy kódrészlet, amelyet egy előre meghatározott számú alkalommal szeretnél megismételni. Az alábbi kódrészlet két for ciklust tartalmaz. (Jelenleg nem szükséges minden szintaktikai elem részletes megértése).
    
### <span style="color:red"> Feladat: </span> 
- ### Megfigyelhető, hogy a kód minden egyes `for` utasítással jobbra mozog.
- ### Futtassuk a kódot `Shift + Enter`paranccsal.

In [39]:
#az első kódblokk, amely két listát definiál
elso_lista=[10,20,30,40]
masodik_lista=[1,2,3,4,5]

for tizes in elso_lista:
    #a második kódblokk (végigmegy az elso_lista elemein)
    print('Belépés a második kódblokkba') 
    for egyes in masodik_lista:
        #minden tizes esetében végigmegy a masodik_lista elemein)
        uj_szam=tizes+egyes
        print('A harmadik kódblokk eredménye; Az új szám:', uj_szam)


Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 11
A harmadik kódblokk eredménye; Az új szám: 12
A harmadik kódblokk eredménye; Az új szám: 13
A harmadik kódblokk eredménye; Az új szám: 14
A harmadik kódblokk eredménye; Az új szám: 15
Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 21
A harmadik kódblokk eredménye; Az új szám: 22
A harmadik kódblokk eredménye; Az új szám: 23
A harmadik kódblokk eredménye; Az új szám: 24
A harmadik kódblokk eredménye; Az új szám: 25
Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 31
A harmadik kódblokk eredménye; Az új szám: 32
A harmadik kódblokk eredménye; Az új szám: 33
A harmadik kódblokk eredménye; Az új szám: 34
A harmadik kódblokk eredménye; Az új szám: 35
Belépés a második kódblokkba
A harmadik kódblokk eredménye; Az új szám: 41
A harmadik kódblokk eredménye; Az új szám: 42
A harmadik kódblokk eredménye; Az új szám: 43
A harmadik kódblokk eredménye; Az új szám: 44
A harmadik

## <span style="color:brown"> 1.2) Üzenet megjelenítése

A legegyszerűbb függvény a Pythonban a print. Szöveg kiírásához egyszerűen írja be:

In [40]:
print("Hello World")

Hello World


**Formázott kimenet**

Bizonyos esetekben szükséges lehet a kimenet formázása, amelyhez a `format` függvény használható. 

A függvény használatával lehetőségünk van adattípusok konvertálására és lebegőpontos számok csonkítására is. Az általános szintaxis:

`[argumentum]:[szélesség][.pontosság]típus`


In [42]:
# Példák a print függvény kimenetének többféle formázására
print('{} {}'.format('egy', 'kettő'))
print('{} {}'.format(1,2))
print('Pi= {}'.format(3.14159))
print('Pi= {0:8.2f}'.format(3.14159))

egy kettő
1 2
Pi= 3.14159
Pi=     3.14


## <span style="color:brown"> 1.3) Megjegyzések
    
Kettőskereszt beírásával tudjuk jelezni a megjegyzést.


In [43]:
# megjegyzés a kódhoz

## <span style="color:brown"> 1.4) Alapvető adattípusok

Mint a legtöbb nyelvben, a Pythonban is léteznek alapvető adattípusok, például egész számok (integers), lebegőpontos számok (floats), logikai értékek (Booleans) és karakterláncok (strings). Ezek az adattípusok hasonlóan viselkednek, mint más programozási nyelvekben.

**Számok (Numbers):** Egész (integer) vagy lebegőpontos (floats) számok 

**Logikai értékek (Booleans):** A Python támogatja a logikai operátorokat, de szimbólumok helyett angol szavakat használ:
-	`and` ÉS
-	`or` VAGY
-	`not` NEM

**Szövegek (Strings):** A karakterláncokat egyes `'` vagy dupla idézőjellel `""` lehet definiálni. 

In [44]:
# egész érték változóhoz rendelése:
myint = 9
print('example integer is ', myint)

# lebegőpontos érték hozzárendelése:
myfloat1=9.3
myfloat2=float(9)
print('example integer is ', myfloat1)
print('casting an integer as a float results in', myfloat2)

# Logikai változók deklarálása:
mybool1 = True
mybool2 = False
print('example booleans are ', mybool1, ' and ', mybool2)

# A szövegek egyszeres vagy dupla idézőjellel definiálhatók: 
string1="hello world"
string2='hello world'
print (string1)
print(string2)
print('testing if string1 and string2 are equal:', string1==string2)

# Példák a szövegeken alkalmazható függvényekre:
s = "hello"
# A string első karakterét nagybetűssé alakítja, a többit kicsivé.
print(s.capitalize())  
# A teljes stringet nagybetűssé alakítja.
print(s.upper())    
# A szöveget jobbra igazítja, és 7 karakter hosszúságúra bővíti úgy, hogy a bal oldalon szóközöket ad hozzá.   
print(s.rjust(7))  
# A szöveget középre igazítja, és 7 karakter hosszúságúra bővíti úgy, hogy szóközöket ad hozzá mindkét oldalán.   
print(s.center(7))     
 # Minden 'l' karaktert '(ell)'-re cserél.
print(s.replace('l', '(ell)')) 
# Eltávolítja a vezető és záró szóközöket a stringből.
print('  world '.strip())



example integer is  9
example integer is  9.3
casting an integer as a float results in 9.0
example booleans are  True  and  False
hello world
hello world
testing if string1 and string2 are equal: True
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


## <span style="color:brown"> 1.5) Operátorok
Az alapvető matematikai operátorok:
- összeadás (`+`)
- kivonás (`-`)
- szorzás (`*`)
- osztás (`/` or `//`)
- maradékos osztás (`%`)
- kitevő (`**`)



In [45]:
# Egyszerű matematikai műveletek példái:
print('összeadás:', 2+3)
print('kivonás:', 2-3)
print('szorzás:', 2*3)
print('osztás:', 2/3)
# A maradék operátor ('%') az osztás utáni egész szám maradékát adja vissza::
a=9
b=5
print('the remainder following division of {} by {} is {}'.format(a, b, a%b))
# A '*' kétszeri használata ('**') hatványozást eredményez
a=2
b=4
print('{} to the power {} is {}'.format(a, b, a**b))

összeadás: 5
kivonás: -1
szorzás: 6
osztás: 0.6666666666666666
the remainder following division of 9 by 5 is 4
2 to the power 4 is 16


## <span style="color:brown"> 1.6) Feltételek

In [46]:
a=10
print(a==10)
print(a<12)
print(a>20)

# Két feltételes kifejezés egyidejű értékelése 'and', 'or' és 'is' operátorokkal
a=10
b=12
print(a is b)
print(a< 15 and b > 10)
print (a < 15 or b < 10)

# A "not" operátor a logikai kifejezés negálására szolgál:
print(not a is b)

True
True
False
False
True
True
True


***

# <span style="color:brown"> Gyakorlat: Változók, operátorok és feltételek

### <span style="color:red"> Gyakorlat 1: A 'print' függvény és szövegek formázása

In [9]:
# Q1. Definiáljunk változókat és írjuk ki őket
# pl. a=8; b=7; teststr='Hello World'

# Q2. Gyakoroljuk a print utasításokat pl. print('hello world')

# Q3. Próbáljuk ki a teststr változó kiíratását (mi történik, ha dupla idézőjeleket használunk?)

# Q4. Próbáljuk meg hozzáadni az 'a' változót a 'teststr' változóhoz egy print utasításban


In [47]:
# Megoldások

# Q1. Definiáljunk változókat és írjuk ki őket
a=8 
b=7
teststr='Hello World'
print(teststr)
print("a={} and b={}" .format(a, b))


# Q2. Gyakoroljuk a print utasításokat pl. print('hello world')
print('hello world')

# Q3. Próbáljuk ki a teststr változó kiíratását (mi történik, ha dupla idézőjeleket használunk?)
teststr="Hello World"
print(teststr)

# Q4. Próbáljuk meg hozzáadni az 'a' változót a 'teststr' változóhoz egy print utasításban
print('{} {}'.format(teststr,a))
print(teststr +' '+ str(a))
print(f"{teststr} {a}")

Hello World
a=8 and b=7
hello world
Hello World
Hello World 8
Hello World 8
Hello World 8


### <span style="color:red"> Gyakorlat 2: Egyszerű műveletek

In [11]:
# Q1. Próbáljunk ki egyszerű matematikai műveleteket, írjuk ki az eredményt:

#print(' a+b = ', )
#print(' a-b = ', )
#print(' a*b = ', )
#print(' a/b = ', )

# Q2. Matematikai operátorok kombinációja, próbáljuk kombinálni a matematikai operátorokat pl. a*a+b - a/b

# Q3. Mi történik a zárójelek hozzáadásával pl. a*(a+b - a/b) vagy (a*a+b - a)/b


In [48]:
# Gyakorlat 2 megoldások

# Q1. Próbáljunk ki egyszerű matematikai műveleteket, írjuk ki az eredményt:
a=8 
b=7

print(' a+b = {}'.format(a+b))
print(' a-b = {}'.format(a-b))
print(' a*b = {}'.format(a*b))
print(' a/b = {:.2f}'.format(a/b))

# Q2. Matematikai operátorok kombinációja, próbáljuk kombinálni a matematikai operátorokat pl. a*a+b - a/b 
print(' a*a+b - a/b = {:.2f}' . format(a*a+b-a/b))

# Q3 Mi történik a zárójelek hozzáadásával pl. a*(a+b - a/b) vagy (a*a+b - a)/b
print(' a*(a+b - a/b) =  {:.2f}' . format(a*(a+b - a/b)))
print(' (a*a+b - a)/b =  {:.2f}' .format((a*a+b -a)/b))


 a+b = 15
 a-b = 1
 a*b = 56
 a/b = 1.14
 a*a+b - a/b = 69.86
 a*(a+b - a/b) =  110.86
 (a*a+b - a)/b =  9.00


### <span style="color:red"> Gyakorlat 3: Feltételek

In [13]:
# Q1. Változók definiálása

a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 Értékeljük az alábbi feltételes állításokat
print('a==b',)
print('2*a==b',)
print('a>b',)
print('a<b',)
print('a is b',)
print('2*a is b',)

# Q3. Kombináljuk a feltételeket and/or operátorokkal és írjuk ki az eredményt. Például: 'a == b or b> a' 


# Q4. Próbáljuk meg az állítások inverzét a not operátorral

a==b
2*a==b
a>b
a<b
a is b
2*a is b


In [49]:
# Gyakorlat 3 megoldások

# Q1. Változók definiálása 

a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 Értékeljük az alábbi feltételes állításokat
print('a==b',a==b)
print('2*a==b',2*a==b)
print('a>b',a>b)
print('a<b',a<b)
print('a is b',a is b)
print('2*a is b',2*a is b)

# Q3. Kombináljuk a feltételeket and/or operátorokkal és írjuk ki az eredményt. Például: 'a == b or b> a' 
print(a==b or b>a)

# Q4. Próbáljuk meg az állítások inverzét a not operátorral
print(not(a==b or b>a))


a==b False
2*a==b True
a>b False
a<b True
a is b False
2*a is b True
True
False


***

# <span style="color:brown"> 2) Listák
    
A lista rendezett objektumok gyűjteménye. A lista elemei nem feltétlenül ugyanabból a típusból kell, hogy álljanak, hanem lehetnek számok, szövegek vagy más típusú objektumok tetszőleges keveréke. A listák más listákat is tartalmazhatnak alkategóriaként. Példák listákra:

In [50]:
emptylist=[] # Üres lista
integerlist=[1,2,3,4,5,6] #Egész számokat tartalmazó lista
stringlist=['string1', 'string2', 'string3'] #Szövegeket tartalmazó lista
mixedlist=[10, "some string", 4.2, 2, 'some other string'] #Vegyes típusú adatokat tartalmazó lista
# beágyazott lista
nestedlist=[['dog','cat','pig'], [1,2,3 ,4], [10, "some string", 4.2, 2, 'some other string'] ]

## <span style="color:brown"> 2.1) Indexálás szekvenciális adattípusokban
    
Az indexálás a szekvenciális adattípusok (pl. lista, tuple, string) elemeinek elérésére szolgál. Az indexek lehetővé teszik, hogy hozzáférjünk a sorozat egy adott eleméhez. Pythonban az indexek 0-tól kezdődnek, tehát <font color='red'> az első elem indexe 0 </font>, a másodiké 1, és így tovább.

In [51]:
teststr = 'Hello World'
print('a harmadik elem az egész számok listájában', integerlist[2])
print('a negyedik elem a vegyes lista elemei között', mixedlist[3])
print('a hetedik elem a szövegben', teststr[6])

# figyeljük meg, hogy a szeletelés az összes elemet tartalmazza a megadott indexig, de a záró indexet nem
print('a középső két elem az egész számok listájában', integerlist[2:4])
# szeletelés a kezdetektől az 5. elemig
print('a kezdetektől a 4. elemig', integerlist[:4])
# szeletelés a 4. elemtől a végéig
print('a 4. elemtől a végéig', integerlist[3:])
# szeletelés a 4. elemtől egy elemmel a vég előtt
print('a 4. elemtől egy elemmel a vég előtt', integerlist[3:-1])
# Az indexálás fordítva is elvégezhető:
print('fordított indexálás', integerlist[::-1])
# vagy nagyobb lépések használatával:
print('minden második elem', integerlist[::2])

a harmadik elem az egész számok listájában 3
a negyedik elem a vegyes lista elemei között 2
a hetedik elem a szövegben W
a középső két elem az egész számok listájában [3, 4]
a kezdetektől a 4. elemig [1, 2, 3, 4]
a 4. elemtől a végéig [4, 5, 6]
a 4. elemtől egy elemmel a vég előtt [4, 5]
fordított indexálás [6, 5, 4, 3, 2, 1]
minden második elem [1, 3, 5]


## <span style="color:brown"> 2.2) Hozzárendelés és módosítás
    
Egy listát az 'append()' függvénnyel tudunk bővíteni

In [52]:
integerlist.append(7)
print('az új egész számok listája', integerlist)

az új egész számok listája [1, 2, 3, 4, 5, 6, 7]


A szövegek és listák hosszát a 'len()' függvény segítségével tudjuk meghatározni:

In [53]:
print('az új egész számok lista hossza', len(integerlist))
print('a teststr hosszúsága', len(teststr))

az új egész számok lista hossza 7
a teststr hosszúsága 11


A listákat össze is tudjuk illeszteni:

In [54]:
print(integerlist+stringlist)

[1, 2, 3, 4, 5, 6, 7, 'string1', 'string2', 'string3']


A listák elemei kicserélhetők új elemekre:

In [55]:
integerlist[3] = 'kicserélt elem'
print(integerlist)

[1, 2, 3, 'kicserélt elem', 5, 6, 7]


***

# <span style="color:brown"> Gyakorlatok:

### <span style="color:red"> Gyakorlat 1: Listák

- ### Hozzunk létre egy listát egész számokból
- ### Irassuk ki a lista hosszát
- ### Index alapján találjuk meg a lista elemeit
- ### Vegyük ki a lista egyik szeletét
- ### Adjunk hozzá egy új, más típusú elemet

In [56]:
# Gyakorlat 1 megoldás.

mylist=[1,2,3,4,5]

# index alapján irassuk ki a mylist elemeit 

print(mylist[0],mylist[1],mylist[3])

# index alapján írjuk ki a lista utolsó elemét

print(mylist[-1])

# index segítségével irassuk ki a lista egy szeletét

print(mylist[1:3])

# adjunk a listához egy új elemet

mylist.append(43110)

1 2 4
5
[2, 3]


### <span style="color:red"> Gyakorlat 2: Műveletek szekvenciális adatokon

In [57]:
string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Q1 Két sztring és két lista összefűzése

# Q2  10 másolat összefűzése


In [58]:
# Gyakorlat 2 megoldás

string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Q1 Két sztring és két lista összefűzése

print(string1+string2)
print(list1+list2)

# Q2  10 másolat összefűzése

print(string1*10)

HelloWorld
['Hello', 'World', "I'm", 'ready', 'toPython']
HelloHelloHelloHelloHelloHelloHelloHelloHelloHello


***
# <span style="color:brown"> 3) NumPy tömbök

NumPy a numerikus számításokhoz kínál gyors és hatékony megoldást. 

## <span style="color:brown"> 3.1) A tömb definíciója

A NumPy tömb egy olyan adatszerkezet, amely több értéket tartalmaz, és minden érték ugyanabból a típusból származik (pl. számok). A tömb elemeit egy olyan index segítségével érhetjük el, amely nem negatív egész számokból áll (pl. 0, 1, 2, ...).
A dimenziók száma a tömb "rangja", azaz hogy hány irányban (dimenzióban) tárolunk adatokat. Például egy 1D tömb egy sor adatot tartalmaz, míg egy 2D tömb egy mátrixot (táblázatot) ábrázol.
A tömb alakja azt mutatja meg, hogy a tömb hány elemet tartalmaz dimenziónként. A NumPy tömböket úgy hozhatjuk létre, hogy Python listákból alakítjuk őket, és az elemekhez szögletes zárójelek segítségével férhetünk hozzá.

In [7]:
# Létrehozunk egy 1D tömböt
a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
# Módosítjuk a tömb egy elemét
a[0] = 5                  
print(a)                 
# Hozzunk létre egy 2D tömböt
b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


A NumPy számos függvényt biztosít a tömbök létrehozására:


In [8]:
# Hozzunk létre egy 2x2-es tömböt, amelynek minden eleme 0
a = np.zeros((2,2))   
print(a)             

# Hozzunk létre egy 1x2-es tömböt, amelynek minden eleme 1
b = np.ones((1,2))    
print(b)              

# Hozzunk létre egy 2x2-es konstans tömböt, ahol minden elem 7
c = np.full((2,2), 7)  
print(c)              

# Hozzunk létre egy 2x2-es egység mátrixot. A 2x2-es egység mátrix egy négyzetes mátrix, amelynek minden átlón kívüli eleme 0, míg az átlójában lévő elemek mind 1-esek.
d = np.eye(2)         
print(d)              

# Hozzunk létre egy 2x2-es tömböt, amelyet véletlenszerű értékek töltenek ki
e = np.random.random((2,2))  
print(e)                    

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.05809331 0.92954297]
 [0.54405483 0.8949076 ]]


    ## <span style="color:brown"> 3.2) Tömb indexelése
    
    A NumPy többféle módot kínál a tömbök indexelésére. Hasonlóan a listákhoz, a NumPy tömbök is szeletelhetők. Mivel a tömbök lehetnek többdimenziósak, minden dimenzióhoz külön szeletet kell megadni:

In [9]:
# Hozzunk létre egy 2D tömböt (3, 4) alakzattal
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

# Használjunk szeletelést a tömb első 2 sorának és 1-2. oszlopának kiválasztására
b = a[:2, 1:3]
print(b)

# Figyeljük meg, hogy a szeletelés egy módja annak, hogy megtekintsük a tömb adatait,
# és ez azt jelenti, hogy a két objektum adatai megosztottak. Ezért ha módosítjuk a 'b'-t,
# akkor az eredeti tömb is módosulni fog.
print(a[0, 1])   # Eredetileg: 2
b[0, 0] = 77     # Módosítjuk a 'b' első elemét
print(a[0, 1])   # Az eredeti tömb is módosult: 77

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


Szám-indexelést és szeletelést is kombinálhatunk. Azonban, ha ezt megtesszük, akkor az eredményül kapott tömb alacsonyabb rangú lesz, mint az eredeti tömb.

In [10]:
# Hozzuk létre a következő, (3, 4) alakú, 2D tömböt
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Ha a második sort szeretnénk kiválasztani, annak két módja van.
# Ha egy sorhoz/oszlophoz egész számokkal indexelve férünk hozzá (a[1, :] vagy a[:, 1]), 1D tömböt kapunk.
# Ha szeleteléssel (a[1:2, :] vagy a[:, 1:2]), 2D tömböt kapunk, amely megőrzi az eredeti dimenziókat.
row_r1 = a[1, :]    # Az 'a' második sorának 1D nézete
row_r2 = a[1:2, :]  # Az 'a' második sorának 2D nézete
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

# Ugyanez vonatkozik a tömb oszlopainak elérésére is:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## <span style="color:brown"> 3.3) Boolean tömb indexelés

A Boolean tömb indexelés lehetővé teszi egy tömb tetszőleges elemeinek kiválasztását. Gyakran ezt a fajta indexelést arra használják, hogy egy tömb azon elemeit válasszák ki, amelyek megfelelnek egy adott feltételnek.

In [11]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Keressük meg azokat az elemeket az 'a' tömbben, amelyek nagyobbak, mint 2.
# Ez egy olyan NumPy tömböt ad vissza, amely Booleán értékeket tartalmaz, és ugyanolyan alakú, mint 'a'.
# A bool_idx jelzi azt, hogy az adott elem nagyobb-e, mint 2.
bool_idx = (a > 2)   

print(bool_idx)     

# Boolean tömb indexelést használunk egy 1D tömb létrehozásához,
# amely csak azokat az elemeket tartalmazza, ahol a bool_idx értéke True.
print(a[bool_idx])  

# A fenti műveletet egyetlen rövid utasítással is végrehajtható:
print(a[a > 2])  

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


***

# <span style="color:brown"> Gyakorlatok: NumPy

### <span style="color:red"> Gyakorlat 1: </span> Írjunk egy NumPy scriptet, amely numerikus értékeket tartalmazó listát egy egydimenziós NumPy tömbbé alakít.

Eredeti lista: [12.23, 13.32, 100, 36.32]

Egydimenziós NumPy tömb: [ 12.23 13.32 100. 36.32]

In [12]:
# Gyakorlat 1 megoldás
l = [12.23, 13.32, 100, 36.32]
print("Eredeti lista:",l)
a = np.array(l)
print("Egydimenziós NumPy tömb: ",a)

Eredeti lista: [12.23, 13.32, 100, 36.32]
Egydimenziós NumPy tömb:  [ 12.23  13.32 100.    36.32]


### <span style="color:red"> Gyakorlat 2: </span> Írjunk egy NumPy scriptet, amely létrehoz egy 10 elemű nullvektort, és a hetedik elem értékét frissíti 11-re

Várt kimenet: 
```
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]```

In [13]:
# Gyakorlat 2 megoldás
x = np.zeros(10)
print(x)
print("A hetedik elem értékének frissítése 11-re")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
A hetedik elem értékének frissítése 11-re
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


### <span style="color:red"> Gyakorlat 3: </span>Írjunk egy NumPy scriptet, amely létrehoz egy 3×3-as mátrixot, amelynek értékei 2-től 10-ig terjednek.

Várt kimenet:
```
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]```

In [14]:
# Gyakorlat 3 megoldás
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### <span style="color:red"> Gyakorlat 4: </span> Írjunk egy NumPy programot, amely létrehoz egy 8x8-as mátrixot, és kitölti sakktábla mintázattal.
(A sakktábla mintázat olyan váltakozó nullát és egyet tartalmazó minta, ahol minden sor és oszlop felváltva tartalmazza a két értéket.)

Sakktábla mintázat:
```
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```




In [15]:
# Gyakorlat 4 megoldás
x = np.ones((3,3))
print("Sakktábla mintázat:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Sakktábla mintázat:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### <span style="color:red"> Gyakorlat 5: </span> Írjunk egy NumPy programot, amely hozzáfűz további értékeket egy tömb végéhez.

Eredeti tömb: 
'[10, 20, 30]'

A további értékek hozzáadását követően:
`[10 20 30 40 50 60 70 80 90]`

In [16]:
# Gyakorlat 5 megoldás
x = [10, 20, 30]
print("Eredeti tömb:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("A további értékek hozzáadását követően:")
print(x)

Eredeti tömb:
[10, 20, 30]
A további értékek hozzáadását követően:
[10 20 30 40 50 60 70 80 90]


### <span style="color:red"> Gyakorlat 6: </span> Írjunk egy NumPy programot, amely megtalálja két tömb közös értékeit 

Array1: '[ 0 10 20 40 60]'

Array2: '[10, 30, 40]'

A közös értékek:'[10 40]'

In [17]:
# Gyakorlat 6 megoldás
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("A két tömb közös értékei:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
A két tömb közös értékei:
[10 40]


***

# <span style="color:brown"> 4) Feltételes `if` utasítások

A döntési fa lépéseihez hasonlóan, a feltételes utasításokat Pythonban az alábbiak szerint lehet megfogalmazni:

if feltétel: utasítás utasítás

A feltételes utasításnak logikai értékre (True/False) kell kiértékelődnie. Az alábbi döntési fa így leírható:
<img src="figures/HF_decision_tree.png" height="400">

In [21]:
LVEF = int(input('Adja meg az LVEF (left ventricular ejection fraction)  értéket: '))

if LVEF > 50:
    print('HFpEF (heart failure with preserved ejection fraction)')
else:
    if LVEF < 40:
        print('HFrEF (heart failure with reduced ejection fraction)')
    else:
        print('HFmEF (heart failure with mildly reduced ejection fraction)')

Adja meg az LVEF (left ventricular ejection fraction)  értéket:  45


HFmEF (heart failure with mildly reduced ejection fraction)


Az összes feltételes utasításforma használható, beleértve az is/and/or utasítások alkalmazását is, például: 

In [19]:
a=10
b=12

if a < 15 and b > 10:
    print('futtasd a következő kódrészletet')


futtasd a következő kódrészletet


Az "in" operátor is használható annak ellenőrzésére, hogy egy adott objektum létezik-e egy listában.
A következő kód ellenőrzi, hogy a name változó értéke szerepel-e a ["John", "Dave"] listában, és ha igen, akkor kiírja, hogy a személy neve vagy "John", vagy "Dave":

In [20]:
name = "John"
if name in ["John", "Dave"]:
    print("A személy neve vagy John vagy Dave.")

A személy neve vagy John vagy Dave.


Az if utasítások sorozata kombinálható if-else utasításokkal, azaz

In [22]:
BMI=20

if BMI <= 18.5: 
    print('A személy alultáplált.')
elif BMI > 18.5 and BMI <=25.0:
    print('A személy normál súlyú.')
elif BMI > 25.0 and BMI <=30.0 :
    print('A személy túlsúlyos.')
else:
    print('A személy elhízott.')


A személy normál súlyú.


***

# <span style="color:brown"> Gyakorlatok:

### <span style="color:red"> Gyakorlat 1: </span> Változtassa meg a BMI értékét és figyelje meg a változást

### <span style="color:red"> Gyakorlat 2: </span> Próbáljuk meg reprodukálni a döntési fát és próbáljuk megváltoztatni a bemeneti értékeket:

<img src="figures/IHCA_decision_tree.png" height="400">

Decision tree from *Li, Hong, et al. "Decision tree model for predicting in‐hospital cardiac arrest among patients admitted with acute coronary syndrome." Clinical Cardiology 42.11 (2019): 1087-1093.*

In [23]:
#Életfunkciót értékelő pontszám bekérése
ViEWS = int(input('Please introduce value for ViEWS: '))
#A betegnél előfordult szívritmuszavar (1: igen, 0: nem) bekérése:
arrhythmia = int(input('Please introduce fatal arrhythmia status (yes = 1, no = 0):'))
#Diabétesz előfordulása (1: igen, 0: nem):
diabetes = int(input('Please introduce diabetes status (yes = 1, no = 0):'))
#A szívelégtelenség súlyosságát jelző osztály (1–4, ahol 1 a legenyhébb, 4 a legsúlyosabb):
Killip = int(input('Please introduce Killip class (class І = 1, II = 2, III = 3, IV = 4):'))
#BUN érték:
BUN = int(input('Please introduce value for blood urea nitrogen (BUN):'))
#Szívspecifikus troponin I érték:
cTnI = int(input('Please introduce value for cardiac troponin I (cTnI):'))
#A beteg életkora:
age = int(input('Please introduce value for age:'))

if ViEWS < 5:
    if arrhythmia:
        if Killip > 2:
            if cTnI >= 28:
                print('High (70%‐100%)')
            else:
                if BUN < 7.9:
                    print('Moderate (40%‐69%)')
                else:
                    print('Low (<40%)')  
        else:
            print('Low (<40%)')

    else:
        print('Low (<40%)')
else:
    if diabetes:
        print('High (70%‐100%)')
    else:
        if age < 64:
            print('Low (<40%)')
        else:
            print('Moderate (40%‐69%)')


Please introduce value for ViEWS:  4
Please introduce fatal arrhythmia status (yes = 1, no = 0): 1
Please introduce diabetes status (yes = 1, no = 0): 1
Please introduce Killip class (class І = 1, II = 2, III = 3, IV = 4): 1
Please introduce value for blood urea nitrogen (BUN): 34
Please introduce value for cardiac troponin I (cTnI): 34
Please introduce value for age: 45


Low (<40%)


***

# <span style="color:brown"> 5) Ciklusok és függvények

## <span style="color:brown"> 5.1) A for utasítás

A for ciklus egy adott sorozat elemein megy végig, és minden egyes elemnél végrehajt egy műveletet. A sorozat lehet például egy lista, egy tartomány (range), egy sztring karakterei vagy más iterálható adatszerkezet.

In [24]:
mylist=[10,20,30,40,50]

for item in mylist:
    print(item)

10
20
30
40
50


Számtartományokhoz a Python a range(start, end, increment) függvényt biztosítja, amely egy sorozatot hoz létre 

In [25]:
for item in range(0,10,2):
    print(item)

0
2
4
6
8


### <span style="color:red"> Gyakorlat: </span> Próbáljuk megváltoztatni a tartományt, adjunk meg különböző lépésközöket, kezdő- és végpontokat.


Az egymásba ágyazott for ciklusok segítségével, egy for ciklus belsejében egy másik for ciklust helyezünk el. Ez lehetővé teszi, hogy több különböző listán vagy tartományon végezzünk el műveleteket, egymásba ágyazottan.

In [26]:
# Az első kódrészlet
# tizesek
elso_lista = [10, 20, 30, 40]  
# egyesek
masodik_lista = [1, 2, 3, 4, 5]

# Az első for ciklus (az elso_lista elemein iterálunk)
for tizes in elso_lista:
    # A második kódrészlet (egy második for ciklus, ami masodik_lista elemein megy végig)
    for egyes in masodik_lista:
        # A harmadik kódrészlet (második lista elemein iterálunk)
        # Minden egyes 'tizes' értékhez hozzáadjuk az 'egyes' értéket.
        uj_szam = tizes + egyes  
        # A harmadik kódrészlet kimenete: Az uj_szam kiszámítása.
        # Az eredmény kiíratása
        print('A harmadik kódrészlet kimenete; Az új szám ', uj_szam)  

A harmadik kódrészlet kimenete; Az új szám  11
A harmadik kódrészlet kimenete; Az új szám  12
A harmadik kódrészlet kimenete; Az új szám  13
A harmadik kódrészlet kimenete; Az új szám  14
A harmadik kódrészlet kimenete; Az új szám  15
A harmadik kódrészlet kimenete; Az új szám  21
A harmadik kódrészlet kimenete; Az új szám  22
A harmadik kódrészlet kimenete; Az új szám  23
A harmadik kódrészlet kimenete; Az új szám  24
A harmadik kódrészlet kimenete; Az új szám  25
A harmadik kódrészlet kimenete; Az új szám  31
A harmadik kódrészlet kimenete; Az új szám  32
A harmadik kódrészlet kimenete; Az új szám  33
A harmadik kódrészlet kimenete; Az új szám  34
A harmadik kódrészlet kimenete; Az új szám  35
A harmadik kódrészlet kimenete; Az új szám  41
A harmadik kódrészlet kimenete; Az új szám  42
A harmadik kódrészlet kimenete; Az új szám  43
A harmadik kódrészlet kimenete; Az új szám  44
A harmadik kódrészlet kimenete; Az új szám  45


**`enumerate`**

Bizonyos esetekben szükség lehet arra, hogy a ciklusban mind a lista elemeit, mind pedig azok indexeit használjuk. Ilyenkor az enumerate függvény használható.

In [27]:
lista=['egy','kettő','három','négy','öt']

for index,item in enumerate(lista):
    print(index,item)

0 egy
1 kettő
2 három
3 négy
4 öt


## <span style="color:brown"> 5.2) Függvények

A függvények lehetővé teszik a kód részek tömör strukturálását, amelyek egy programon (vagy akár több programon) belül többször is használatra kerülnek. 

A Pythonban függvényt a 'def' kulcsszóval definiáljuk:

``` 
def myfunction(arg1, arg2, arg3):  # függvény definíció (opcionális bemeneti argumentumokkal)
    
    a kód törzse, amelyet többször ismételni kell
    
    return someval1, someval2 

Figyeljük meg a kettőspontot a függvény fejlécében, és a behúzás használatát a függvény törzsén belül. A függvényen belül olyan kódsorok találhatók, amelyeket egyébként többször is ismételni kellene a programban. A függvény ezután visszaadja az eredményeket. Egyszerű függvények esetén a függvény egy sorban is visszaadható, például:

In [28]:
# függvény definíció
def sum(x, y):
    return x + y  # mivel a függvény egyszerű, egy sorban is visszaadható

# függvény alkalmazása

a = 5
b = 10

print('a {} és b {} összege: {}'.format(a, b, sum(a, b)))

a 5 és b 10 összege: 15


Az opcionális bemeneti argumentumok alapértelmezett értékekkel is megadhatók, például:

In [29]:
# ez a függvény így 2 vagy 3 argumentum összegét is visszaadhatja
def sum2(x, y, z=0):
    return x + y + z 

# függvény alkalmazása

a = 5
b = 10
c = 20

print('a {} és b {} összege: {}'.format(a, b, sum2(a, b)))
print('a {}, b {} és c {} összege: {}'.format(a, b, c, sum2(a, b, c)))

a 5 és b 10 összege: 15
a 5, b 10 és c 20 összege: 35


Az opcionális argumentumokat úgy is megadhatjuk, hogy pontosan meghatározzuk, melyik argumentumot szeretnénk használni kulcsszavak (keyword) segítségével (az argumentum nevének hivatkozásával a függvényhívás során):

In [30]:
def sumsub(x, y, z1=0, z2=0):
    return x - y + z1 - z2

# a függvény alkalmazása

a=5
b=10
c=20
d=30

print(sumsub(12,4))
print(sumsub(42,15,z2=10))
print(sumsub(42,15,z1=20, z2=10))

8
17
37


***

# <span style="color:brown"> Gyakorlatok:ciklusok és függvények

### <span style="color:red"> Gyakorlat 1: </span> Írjon egy függvényt, amely bemeneti paraméterként a szisztolés és diasztolés vérnyomásértéket kapja, és kiírja, hogy a vizsgált személy melyik kategóriába tartozik az alábbi táblázat alapján.:
<img src="figures/BloodPressure.png" height="400">

In [31]:
# Vérnyomás függvény
def blood_pressure(systolic_bp, diastolic_bp):
  # itt írjuk meg a kódot 
  print('Write your code here')

systolic_bp = int(input('Kérem adja meg a szisztolés vérnyomás értékét: '))
diastolic_bp = int(input('Kérem adja meg a diasztolés vérnyomás értékét: '))
blood_pressure(systolic_bp, diastolic_bp)

Kérem adja meg a szisztolés vérnyomás értékét:  134
Kérem adja meg a diasztolés vérnyomás értékét:  98


Write your code here


In [32]:
def blood_pressure(systolic_bp, diastolic_bp):
    if (systolic_bp < 120 and diastolic_bp < 80):
        print('Normal')
    elif (120 < systolic_bp <= 129 and diastolic_bp < 80):
        print('Elevated')
    elif (130 <= systolic_bp <= 139 or 80 <= diastolic_bp < 89):
        print('High blood pressure, hypertension stage 1')
    elif (systolic_bp > 180 or diastolic_bp > 120):
        print('High blood pressure. Consult your doctor immediately.')
    elif (140 <= systolic_bp < 180 or 90 <= diastolic_bp < 120):
        print('High blood pressure, hypertension stage 2')

blood_pressure(systolic_bp, diastolic_bp)

High blood pressure, hypertension stage 1


### <span style="color:red"> Gyakorlat 2: </span>  Irjunk egy ciklust, amely 10 beteget minősít a szisztolés és a diasztolés vérnyomás értékek alapján. Használjunk for ciklust

In [34]:
# 10 ismétlés a 10 beteg kiértékeléséhez:
for i in np.arange(10):
    #szisztolés vérnyomás generálása 90 és 200 Hgmm között
    systolic_bp = random.randint(90, 200)
    #diasztolés vérnyomás generálása 60 és 130 Hgmm között
    diastolic_bp = random.randint(60, 130)
    #Kiírjuk az aktuális beteg szisztolés és diasztolés vérnyomását
    print('Subject {} -> Systolic bp = {} and diastolic bp = {}'.format(i, systolic_bp, diastolic_bp))
    #Meghívjuk a blood_pressure függvényt, amely kategorizálja a vérnyomást
    blood_pressure(systolic_bp, diastolic_bp)

Subject 0 -> Systolic bp = 169 and diastolic bp = 96
High blood pressure, hypertension stage 2
Subject 1 -> Systolic bp = 132 and diastolic bp = 84
High blood pressure, hypertension stage 1
Subject 2 -> Systolic bp = 170 and diastolic bp = 79
High blood pressure, hypertension stage 2
Subject 3 -> Systolic bp = 131 and diastolic bp = 97
High blood pressure, hypertension stage 1
Subject 4 -> Systolic bp = 101 and diastolic bp = 90
High blood pressure, hypertension stage 2
Subject 5 -> Systolic bp = 187 and diastolic bp = 126
High blood pressure. Consult your doctor immediately.
Subject 6 -> Systolic bp = 133 and diastolic bp = 73
High blood pressure, hypertension stage 1
Subject 7 -> Systolic bp = 137 and diastolic bp = 89
High blood pressure, hypertension stage 1
Subject 8 -> Systolic bp = 139 and diastolic bp = 129
High blood pressure, hypertension stage 1
Subject 9 -> Systolic bp = 191 and diastolic bp = 94
High blood pressure. Consult your doctor immediately.
